The ROS portion of the survey that we will examine contains values that are duplicated at the household level when the survey is broken out by the individuals within each household. We will attempt to find all of the columns containing duplicate values across each entire household to ensure that the analysis done by our team is not skewed by larger households.

This survey was conducted by the Fafo Research Foundation in conjunction with Institut Haïtien de l’Enfance.

We will first upload libraries and the file

In [149]:
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import seaborn as sns
import pandas_profiling as pp
%matplotlib inline

In [150]:
df = pd.read_csv('FAFO_ROS.csv')
df.head()

Exception ignored in: <bound method Workbook.__del__ of <xlsxwriter.workbook.Workbook object at 0x11af50400>>
Traceback (most recent call last):
  File "/Users/andrewmurphy/anaconda/lib/python3.6/site-packages/xlsxwriter/workbook.py", line 149, in __del__
    raise Exception("Exception caught in workbook destructor. "
Exception: Exception caught in workbook destructor. Explicit close() may be required for workbook.
Exception ignored in: <bound method ZipFile.__del__ of <zipfile.ZipFile [closed]>>
Traceback (most recent call last):
  File "/Users/andrewmurphy/anaconda/lib/python3.6/zipfile.py", line 1650, in __del__
    self.close()
  File "/Users/andrewmurphy/anaconda/lib/python3.6/zipfile.py", line 1668, in close
    self._write_end_record()
  File "/Users/andrewmurphy/anaconda/lib/python3.6/zipfile.py", line 1770, in _write_end_record
    self.fp.write(endrec)
  File "/Users/andrewmurphy/anaconda/lib/python3.6/zipfile.py", line 721, in write
    n = self.fp.write(data)
  File "/Users/andrewmurphy/anaconda/lib/python3.6/site-packages/pandas/core/generic.py", line 4376, in __getattr__
    return object.__getattribute__(self, name)
AttributeError: 'DataFrame' object has no attribute 'write'
/Users/andrewmurphy/anaconda/lib/python3.6/site-packages/IPython/core/interactiveshell.py:2717: DtypeWarning: Columns (58,61,247,248,249,473,476,481,496,501,502,503,514,630) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

   Unnamed: 0     HH_key   HHexpweigh  RSIexpweigh  HHrelweigh  RSIrelweigh  Stratum  ImplicitStratum  ClusterID DepartementCode   ...   SM10new SM19new SM27new  ED02new                    ED04new    LD21new    LD22new    LD23new   HourSleep HH03new
0  1           1001_1309  2874.540223  3328.590909  3.619299    2.690686     12       5                10         Northeast        ...    NaN     NaN     NaN     NaN      NaN                        NaN        NaN        NaN        NaN         NaN
1  2           1001_1309  2874.540223  3328.590909  3.619299    2.690686     12       5                10         Northeast        ...    NaN     NaN     NaN     NaN      NaN                        NaN        NaN        NaN        NaN         NaN
2  3           1001_1309  2874.540223  3328.590909  3.619299    2.690686     12       5                10         Northeast        ...    NaN     NaN     10-14   6 years  Not enrolled in any level  5-6 hours  3-4 hours  1-2 hours  9-11 hours  NaN
3  4           1002_1374  228.362714   463.015530   0.287529    0.374281     12       5                10         Northeast        ...    NaN     NaN     NaN     NaN      NaN                        NaN        NaN        NaN        NaN         NaN
4  5           1002_1374  228.362714   463.015530   0.287529    0.374281     12       5                10         Northeast        ...    NaN     NaN     NaN     NaN      NaN                        NaN        NaN        NaN        NaN         NaN

[5 rows x 708 columns]

With 708 columns in the data, we wouldn't be able to spot check each one for duplicates.
To find the columns with repeated answers, we will find the 1 household with the most number of members to test whether they have repeated answers in the survey.

In [151]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10876 entries, 0 to 10875
Columns: 708 entries, Unnamed: 0 to HH03new
dtypes: float64(34), int64(10), object(664)
memory usage: 58.7+ MB

In [152]:
df2 = df[['HH_key', 'HHexpweigh']]
df2.head()

      HH_key   HHexpweigh
0  1001_1309  2874.540223
1  1001_1309  2874.540223
2  1001_1309  2874.540223
3  1002_1374  228.362714
4  1002_1374  228.362714

In [153]:
df3 = df2.pivot_table(values='HHexpweigh', index='HH_key', aggfunc='count')

Household 5227_582 has the most members in its home with 18.

In [154]:
df3 = df3.sort_values('HHexpweigh',ascending=False).head()
df3 = df3.reset_index()
df3.head(3)

      HH_key  HHexpweigh
0  5227_582   18
1  2405_1021  17
2  4503_1444  17

In [155]:
df1 = df[df['HH_key'].isin(['5227_582'])]
df1['HH_key'].value_counts()

5227_582    18
Name: HH_key, dtype: int64

Now our dataset contains only the household that we are testing.

Next, we will create a dataset comprised only of columns with 1 unique value across the 18 different rows.

In [156]:
new_df = df1.loc[:,df1.apply(pd.Series.nunique) == 1]
new_df

        HH_key  HHexpweigh  RSIexpweigh  HHrelweigh  RSIrelweigh  Stratum  ImplicitStratum  ClusterID DepartementCode RegionCode   ...   MI20Anew  WC23_27            WC24_29            WC25_31  HT31new  HT35new  HT66new HT73Ad HT73Ch SM10new
6532  5227_582  725.306373  4468.38843   0.913224    3.612049     41       26               52         West            West        ...    1 time   Did not  Less than 4 hours  Less than 4 hours  No       3.0      Daily    2      1      NaN
6533  5227_582  725.306373  4468.38843   0.913224    3.612049     41       26               52         West            West        ...    1 time   Did not  Less than 4 hours  Less than 4 hours  No       3.0      Daily    2      1      NaN
6534  5227_582  725.306373  4468.38843   0.913224    3.612049     41       26               52         West            West        ...    1 time   Did not  Less than 4 hours  Less than 4 hours  No       3.0      Daily    2      1      NaN
6535  5227_582  725.306373  4468.38843   0.913224    3.612049     41       26               52         West            West        ...    1 time   Did not  Less than 4 hours  Less than 4 hours  No       3.0      Daily    2      1      NaN
6536  5227_582  725.306373  4468.38843   0.913224    3.612049     41       26               52         West            West        ...    1 time   Did not  Less than 4 hours  Less than 4 hours  No       3.0      Daily    2      1      NaN
6537  5227_582  725.306373  4468.38843   0.913224    3.612049     41       26               52         West            West        ...    1 time   Did not  Less than 4 hours  Less than 4 hours  No       3.0      Daily    2      1      NaN
6538  5227_582  725.306373  4468.38843   0.913224    3.612049     41       26               52         West            West        ...    1 time   Did not  Less than 4 hours  Less than 4 hours  No       3.0      Daily    2      1      No
6539  5227_582  725.306373  4468.38843   0.913224    3.612049     41       26               52         West            West        ...    1 time   Did not  Less than 4 hours  Less than 4 hours  No       3.0      Daily    2      1      NaN
6540  5227_582  725.306373  4468.38843   0.913224    3.612049     41       26               52         West            West        ...    1 time   Did not  Less than 4 hours  Less than 4 hours  No       3.0      Daily    2      1      NaN
6541  5227_582  725.306373  4468.38843   0.913224    3.612049     41       26               52         West            West        ...    1 time   Did not  Less than 4 hours  Less than 4 hours  No       3.0      Daily    2      1      NaN
6542  5227_582  725.306373  4468.38843   0.913224    3.612049     41       26               52         West            West        ...    1 time   Did not  Less than 4 hours  Less than 4 hours  No       3.0      Daily    2      1      No
6543  5227_582  725.306373  4468.38843   0.913224    3.612049     41       26               52         West            West        ...    1 time   Did not  Less than 4 hours  Less than 4 hours  No       3.0      Daily    2      1      NaN
6544  5227_582  725.306373  4468.38843   0.913224    3.612049     41       26               52         West            West        ...    1 time   Did not  Less than 4 hours  Less than 4 hours  No       3.0      Daily    2      1      NaN
6545  5227_582  725.306373  4468.38843   0.913224    3.612049     41       26               52         West            West        ...    1 time   Did not  Less than 4 hours  Less than 4 hours  No       3.0      Daily    2      1      NaN
6546  5227_582  725.306373  4468.38843   0.913224    3.612049     41       26               52         West            West        ...    1 time   Did not  Less than 4 hours  Less than 4 hours  No       3.0      Daily    2      1      NaN
6547  5227_582  725.306373  4468.38843   0.913224    3.612049     41       26               52         West            West        ...    1 time   Did not  Less than 4 hours  Less than 4 hours  No       3.0      Daily    2      1      NaN
6548  5227_582  725.306373  4468.38843   0.913224    3.612049     41       26               52         West            West        ...    1 time   Did not  Less than 4 hours  Less than 4 hours  No       3.0      Daily    2      1      No
6549  5227_582  725.306373  4468.38843   0.913224    3.612049     41       26               52         West            West        ...    1 time   Did not  Less than 4 hours  Less than 4 hours  No       3.0      Daily    2      1      NaN

[18 rows x 425 columns]

We can find 425 columns that fit this criteria and have created a list of these columns.

In [157]:
new_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 18 entries, 6532 to 6549
Columns: 425 entries, HH_key to SM10new
dtypes: float64(16), int64(8), object(401)
memory usage: 59.9+ KB

In [158]:
df_list = []

In [159]:
for x in new_df.columns:
    df_list.append(x)

In [160]:
newer_df = pd.DataFrame(index=df_list)
newer_df = newer_df.reset_index()
newer_df.head()

         index
0  HH_key
1  HHexpweigh
2  RSIexpweigh
3  HHrelweigh
4  RSIrelweigh

We can now match this listing to another file that contains the column names.

In [161]:
labels = pd.read_csv('LabelDescriptionFAFO_ROS.csv')

In [162]:
labels.head()

   Unnamed: 0         name                       label
0  1           HH_key       Housheold ID
1  2           HHexpweigh   Household expansion weight
2  3           RSIexpweigh  RSI expansion weigh
3  4           HHrelweigh   Household relative weight
4  5           RSIrelweigh  RSI relative weight

In [163]:
df_labels = newer_df.merge(labels, left_on = 'index', right_on = 'name')
df_labels.head()

         index  Unnamed: 0         name                       label
0  HH_key       1           HH_key       Housheold ID
1  HHexpweigh   2           HHexpweigh   Household expansion weight
2  RSIexpweigh  3           RSIexpweigh  RSI expansion weigh
3  HHrelweigh   4           HHrelweigh   Household relative weight
4  RSIrelweigh  5           RSIrelweigh  RSI relative weight

In [164]:
df_final = df_labels[['index', 'label']]
df_final

                        index                                                                                          label
0    HH_key                    Housheold ID
1    HHexpweigh                Household expansion weight
2    RSIexpweigh               RSI expansion weigh
3    HHrelweigh                Household relative weight
4    RSIrelweigh               RSI relative weight
5    Stratum                   Stratum ID
6    ImplicitStratum           Implicit stratum ID
7    ClusterID                 Cluster ID
8    DepartementCode           Department
9    RegionCode                Region
10   Area                      Area
11   Ville_quartier_ZoneRural  Area
12   AI01                      Departement
13   AI03                      Section commune
14   AI05                      Cluster number
15   AI06                      Sequential number of cluster
16   AI07                      Number of questionnaire
17   AI08                      Number of structure
18   AS05                      Date of interview of household questionnaire
19   AS06                      Start of interview of household questionnaire
20   AS07                      End of interview of household questionnaire
21   AI12                      Date of interview of RSI questionnaire
22   AI13                      Start of interview of RSI questionnaire
23   AI14                      End of interview of RSI questionnaire
24   AS09                      Number of household members
25   AS10                      Roster ID of main respondent
26   AS11                      Roster ID of RSI responsent
27   RSIparID                  Roster ID of RSI respondent's parent/guardian
28   AR1                       Interview status of household questionnaire
29   AI15                      Interview status of RSI questionnaire
..    ...                                                        ...
395  ImproWater                access to improved water source
396  ImproSani                 Access to improved sanitation
397  HHsex                     Gender of household head
398  HHage                     Age of household head
399  HHedu                     Highest level of education completed of household head
400  LHH                       Literacy French and/or Creole of household head
401  RSIsex                    Gender of RSI respondent
402  RSIage                    Age of RSI respondent
403  RSIedu                    Highest level of education completed of RSI respondent
404  RSIenroll                 Current school attendance for RSI respondent
405  RSIcds                    Child domestic status of RSI respondent
406  RSIdepressidx             Depression index for RSI respondent
407  RSIdepressidx5            Quintile of depression index for RSI respondent
408  HU06new                   Electricity supply
409  HE57new                   Total household income last month
410  HE58new                   Total household income last 12 months
411  MI06new                   Residence of mother
412  MI10new                   Residence of mother
413  MI13new                   Place of birth
414  MI14new                   Residence of mother
415  MI20Anew                  Number of places ever lived in outside place of birth
416  WC23_27                   Time spend on household tasks the day before
417  WC24_29                   Time spend on household tasks last saturday
418  WC25_31                   Time spend on household tasks last sunday
419  HT31new                   Being allowed to leave house alone
420  HT35new                   Number of meals at home yesterday
421  HT66new                   Contact with parents past 12 months among relocated children
422  HT73Ad                    Number of adults in household in which relocated children were born by the time he/she left
423  HT73Ch                    Number of children in household in which relocated children were born by the time he/she left
424  SM10new                   Contacts with mother

[425 rows x 2 columns]

We will now expand the screen parameters so that all columns and their names can be easily shown.

In [165]:
pd.set_option('display.expand_frame_repr', False)

In [166]:
pd.set_option('display.max_colwidth', -1)

In [167]:
from pandas import DataFrame
from IPython.display import HTML
HTML(DataFrame(df_final).to_html())

The cleaning is complete!

In this notebook we walked through:
-Data cleaning
-Data analysis
-Uploading/merging different files